# Generated by Django 2.2.5 on 2021-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=246)),
                ('last_name', models.CharField(max_length=246)),
                ('email', models.EmailField(max_length=246, unique=True)),
            ],
        ),
    ]
